version: "3.8"
services:
  mongodb:
    image: mongo:4.2.10
    container_name: mongo_database
    ports:
      - "27017:27017"
    volumes:
      - "./mongo/data:/data/db" 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ias_root
      - MONGO_INITDB_ROOT_PASSWORD=basikali
      - MONGO_INITDB_DATABASE=test
    networks:
      - default

  frontend:
    build: ./IASClient
    container_name: frontend
    ports:
      - "4200:4200"
    networks:
      - default
  
  backend:
    build: ./IASServer
    container_name: backend
    ports:
     - "8080:8080"
    environment:
     - PORT=8080


networks:
  default:
