version: '3.0' # specify docker-compose version
 
# Define the services/ containers to be run
services:
 back: # name of the first service
  build: IASServer # specify the directory of the Dockerfile
  ports:
  - "3000:3000" # specify port mapping
  depends_on: 
    - database
  volumes: 
    - "../Certifies/:/Certifies"
 
 front: # name of the second service
  build: IASClient # specify the directory of the Dockerfile
  ports:
  - "4200:4200" #specify ports mapping
  volumes: 
  - "../Certifies/:/Certifies"

 
 database: # name of the third service
  image: mongo # specify image to build container from
  ports:
  - "27017:27017" # specify port forwarding
