FROM node:12.16.1-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build --prod

FROM nginx:1.19.3

COPY --from=builder /usr/src/app/dist/iasclient/ /usr/share/nginx/html
